spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/mpos
spring.datasource.username=root
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=update
server.port=8080